[package]
name = "liftoff-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
bytes = "1.11.0"
crc = "3.4.0"
num_enum = "0.7.5"
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = "2.0.17"
